### ISSUE TITLE
hrpsysのリアルタイムスレッドとは別なスレッド

### ISSUE THREAD

**Issue by snozawa** [fkanehiro/hrpsys-base#1028]
初歩的な質問ですが、失礼いたします。
hrpsysのリアルタイムスレッドとは別なスレッドは、非リアルタイムなスレッドでしょうか。
具体的には、hrpsys-base/ec/hrpEC以下のARTLinuxもしくはlow latencyのlinuxで、
これらのhrpECを使っている時に、メインスレッドはリアルタイムスレッド（art_enterしていたり優先度をあげてSCHED_FIFOしてたり）になってると思います。
このときに、このhrpsys上でうごく
- 各RTCのなかでかってにつくっているスレッド
- OpenRTMのデータポート通信用などのスレッド

などは、非リアルタイムなスレッドとなりますでしょうか（プロセスをモニタするコマンド等ではそのようにみえました）
もう少しupstreamな疑問かとも思いましたが、上記の別々なOSやhrpECなどもありましたので、
こちらにて質問させていただきました。

よろしくお願いいたします。

**Comment by fkanehiro** [comment]
はい、その通りかと思います。

**Comment by snozawa** [comment]
ありがとうございます。
