### ISSUE TITLE
setTargetPoseRelative not interrupts

### ISSUE THREAD

**Issue by 130s** [fkanehiro/hrpsys-base#1121]
Originally discussed at https://github.com/start-jsk/hrpsys/issues/35#issuecomment-42908811

`wait=False` にしても，冒頭に [waitInterpolationOfGroup](https://github.com/fkanehiro/hrpsys-base/blob/b9389e2e03ac13f0b0cfb105278997302dcc926e/python/hrpsys_config.py#L1474) があるので待ってしまうため，ユーザからすると不具合に見える．

**Comment by k-okada** [comment]
待たないとrelativeた目標位置が計算出来ないと思います．

--
◉ Kei Okada


2017-03-24 12:42 GMT+09:00 Isaac I.Y. Saito <notifications@github.com>:

**Comment by 130s** [comment]
Thanks, document added in #1135.
