### ISSUE TITLE
Issue in installation

### ISSUE THREAD

**Issue by mohamadmahdavian** [fkanehiro/hrpsys-base#1278]
Hello

I get following error while making the package. Do you have any idea what might be the problem here?
[  0%] Built target hrpIo
[  0%] Built target Joystick
[  1%] Built target JoystickComp
[  2%] Built target Joystick2Velocity2D
[ 20%] Built target hrpsysBaseStub
[ 20%] Built target Joystick2Velocity3DComp
[ 20%] Built target Joystick2Velocity2DComp
[ 21%] Built target Joystick2Velocity3D
[ 22%] Built target Joystick2PanTiltAngles
[ 22%] Built target Joystick2PanTiltAnglesComp
[ 22%] Built target ForwardKinematicsComp
[ 23%] Built target ForwardKinematics
[ 24%] Built target HGcontrollerComp
[ 24%] Built target HGcontroller
[ 25%] Built target Range2PointCloud
[ 25%] Built target Range2PointCloudComp
[ 26%] Built target ImpedanceController
[ 27%] Built target JointPathExC
[ 28%] Built target testImpedanceOutputGenerator
[ 29%] Built target ImpedanceControllerComp
[ 30%] Built target testPreviewController
[ 32%] Built target testGaitGenerator
[ 34%] Built target AutoBalancer
[ 35%] Built target SoftErrorLimiter
[ 36%] Built target SoftErrorLimiterComp
[ 38%] Built target AutoBalancerComp
[ 39%] Built target VirtualForceSensorComp
[ 40%] Built target VirtualForceSensor
[ 41%] Built target GraspControllerComp
[ 42%] Built target GraspController
[ 42%] Built target TorqueFilterComp
[ 43%] Built target TorqueFilter
[ 43%] Built target testIIRFilter
[ 43%] Built target KalmanFilterComp
[ 44%] Built target KalmanFilter
[ 44%] Built target testKalmanFilterEstimation
[ 44%] Built target testKFilter
[ 45%] Built target Stabilizer
[ 46%] Built target testZMPDistributor
[ 47%] Built target testTwoDofController
[ 49%] Built target StabilizerComp
[ 50%] Built target RemoveForceSensorLinkOffset
[ 50%] Built target ServoController
[ 51%] Built target RemoveForceSensorLinkOffsetComp
[ 51%] Built target testServoSerial
[ 52%] Built target ServoControllerComp
[ 52%] Built target ThermoEstimator
[ 53%] Built target ThermoEstimatorComp
[ 54%] Built target ThermoLimiter
[ 54%] Built target ThermoLimiterComp
[ 56%] Built target TorqueController
[ 58%] Built target TorqueControllerComp
[ 58%] Building CXX object rtc/ImageData2CameraImage/CMakeFiles/ImageData2CameraImage.dir/ImageData2CameraImage.o
[ 60%] Built target testMotorTorqueController
[ 60%] Building CXX object rtc/ImageData2CameraImage/CMakeFiles/ImageData2CameraImageComp.dir/ImageData2CameraImage.o
[ 60%] Built target ExtractCameraImage
[ 61%] Built target ExtractCameraImageComp
[ 62%] Built target CaptureControllerComp
[ 63%] Built target CaptureController
[ 64%] Built target RangeNoiseMixer
Scanning dependencies of target AverageFilterComp
[ 64%] Built target RangeNoiseMixerComp
Scanning dependencies of target AverageFilter
[ 64%] Building CXX object rtc/AverageFilter/CMakeFiles/AverageFilter.dir/AverageFilter.o
[ 64%] Building CXX object rtc/AverageFilter/CMakeFiles/AverageFilterComp.dir/AverageFilterComp.o
In file included from /usr/include/openrtm-1.2/rtm/InPort.h:39:0,
                 from /usr/include/openrtm-1.2/rtm/DataInPort.h:23,
                 from /home/mohammad/catkin_ws/lipm/hrpsys-base/rtc/ImageData2CameraImage/ImageData2CameraImage.h:18,
                 from /home/mohammad/catkin_ws/lipm/hrpsys-base/rtc/ImageData2CameraImage/ImageData2CameraImage.cpp:10:
/usr/include/openrtm-1.2/rtm/Timestamp.h: In instantiation of ‘RTC::Timestamp<DataType>::ReturnCode RTC::Timestamp<DataType>::operator()(RTC::ConnectorInfo&, DataType&) [with DataType = Img::ImageData; RTC::Timestamp<DataType>::ReturnCode = RTC::ConnectorListenerStatus::Enum]’:
/home/mohammad/catkin_ws/lipm/hrpsys-base/rtc/ImageData2CameraImage/ImageData2CameraImage.cpp:168:2:   required from here
/usr/include/openrtm-1.2/rtm/Timestamp.h:40:20: error: ‘struct Img::ImageData’ has no member named ‘tm’
       data.tm.sec  = tm.sec();
                    ^
/usr/include/openrtm-1.2/rtm/Timestamp.h:41:20: error: ‘struct Img::ImageData’ has no member named ‘tm’
       data.tm.nsec = tm.usec() * 1000;
                    ^
In file included from /usr/include/openrtm-1.2/rtm/InPort.h:39:0,
                 from /usr/include/openrtm-1.2/rtm/DataInPort.h:23,
                 from /home/mohammad/catkin_ws/lipm/hrpsys-base/rtc/ImageData2CameraImage/ImageData2CameraImage.h:18,
                 from /home/mohammad/catkin_ws/lipm/hrpsys-base/rtc/ImageData2CameraImage/ImageData2CameraImage.cpp:10:
/usr/include/openrtm-1.2/rtm/Timestamp.h: In instantiation of ‘RTC::Timestamp<DataType>::ReturnCode RTC::Timestamp<DataType>::operator()(RTC::ConnectorInfo&, DataType&) [with DataType = Img::ImageData; RTC::Timestamp<DataType>::ReturnCode = RTC::ConnectorListenerStatus::Enum]’:
/home/mohammad/catkin_ws/lipm/hrpsys-base/rtc/ImageData2CameraImage/ImageData2CameraImage.cpp:168:2:   required from here
/usr/include/openrtm-1.2/rtm/Timestamp.h:40:20: error: ‘struct Img::ImageData’ has no member named ‘tm’
       data.tm.sec  = tm.sec();
                    ^
/usr/include/openrtm-1.2/rtm/Timestamp.h:41:20: error: ‘struct Img::ImageData’ has no member named ‘tm’
       data.tm.nsec = tm.usec() * 1000;
                    ^
rtc/ImageData2CameraImage/CMakeFiles/ImageData2CameraImage.dir/build.make:62: recipe for target 'rtc/ImageData2CameraImage/CMakeFiles/ImageData2CameraImage.dir/ImageData2CameraImage.o' failed
make[2]: *** [rtc/ImageData2CameraImage/CMakeFiles/ImageData2CameraImage.dir/ImageData2CameraImage.o] Error 1
CMakeFiles/Makefile2:3476: recipe for target 'rtc/ImageData2CameraImage/CMakeFiles/ImageData2CameraImage.dir/all' failed
make[1]: *** [rtc/ImageData2CameraImage/CMakeFiles/ImageData2CameraImage.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 65%] Building CXX object rtc/AverageFilter/CMakeFiles/AverageFilterComp.dir/AverageFilter.o
rtc/ImageData2CameraImage/CMakeFiles/ImageData2CameraImageComp.dir/build.make:75: recipe for target 'rtc/ImageData2CameraImage/CMakeFiles/ImageData2CameraImageComp.dir/ImageData2CameraImage.o' failed
make[2]: *** [rtc/ImageData2CameraImage/CMakeFiles/ImageData2CameraImageComp.dir/ImageData2CameraImage.o] Error 1
CMakeFiles/Makefile2:3513: recipe for target 'rtc/ImageData2CameraImage/CMakeFiles/ImageData2CameraImageComp.dir/all' failed
make[1]: *** [rtc/ImageData2CameraImage/CMakeFiles/ImageData2CameraImageComp.dir/all] Error 2
[ 65%] Linking CXX shared library ../../lib/AverageFilter.so
[ 65%] Built target AverageFilter
[ 65%] Linking CXX executable ../../bin/AverageFilterComp
[ 65%] Built target AverageFilterComp
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

Thank You

**Comment by fkanehiro** [comment]
You seems to be using OpenRTM-1.2 but I have never tried it.

**Comment by mohamadmahdavian** [comment]
Can I know which version have you used for ubuntu 16.04?

Thank you

**Comment by fkanehiro** [comment]
I'm using OpenRTM-1.1.2.

**Comment by mohamadmahdavian** [comment]
Ok. Thank you

**Comment by mohamadmahdavian** [comment]
Is it possible for you to send me the link for OpenRTM-1.1.2 installation. I have spend a long time for finding it,but I wasn't able to find 1.1.2 version.

Thank You

**Comment by fkanehiro** [comment]
Please visit:
https://www.openrtm.org/openrtm/node/6040

**Comment by mohamadmahdavian** [comment]
Thank You for your help. I was able to install openrtm-1.1.2. But I still have an error while making the package.Do you have any idea about this one?

Scanning dependencies of target JoystickComp
Scanning dependencies of target hrpIo
Scanning dependencies of target Joystick
[  0%] Generating PCDLoaderService.hh, PCDLoaderServiceSk.cpp, PCDLoaderServiceDynSk.cpp
[  0%] Building CXX object rtc/Joystick/CMakeFiles/JoystickComp.dir/JoystickComp.o
[  0%] Building CXX object rtc/Joystick/CMakeFiles/Joystick.dir/Joystick.o
[  0%] Building CXX object lib/io/CMakeFiles/hrpIo.dir/iob.o
In file included from /home/mohammad/catkin_ws/lipm/hrpsys-base/rtc/Joystick/Joystick.cpp:10:0:
/home/mohammad/catkin_ws/lipm/hrpsys-base/rtc/Joystick/Joystick.h:13:36: fatal error: rtm/idl/BasicDataType.hh: No such file or directory
compilation terminated.
/home/mohammad/catkin_ws/lipm/hrpsys-base/rtc/Joystick/JoystickComp.cpp:10:25: fatal error: rtm/Manager.h: No such file or directory
compilation terminated.
rtc/Joystick/CMakeFiles/Joystick.dir/build.make:62: recipe for target 'rtc/Joystick/CMakeFiles/Joystick.dir/Joystick.o' failed
make[2]: *** [rtc/Joystick/CMakeFiles/Joystick.dir/Joystick.o] Error 1
CMakeFiles/Makefile2:1204: recipe for target 'rtc/Joystick/CMakeFiles/Joystick.dir/all' failed
make[1]: *** [rtc/Joystick/CMakeFiles/Joystick.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
rtc/Joystick/CMakeFiles/JoystickComp.dir/build.make:62: recipe for target 'rtc/Joystick/CMakeFiles/JoystickComp.dir/JoystickComp.o' failed
make[2]: *** [rtc/Joystick/CMakeFiles/JoystickComp.dir/JoystickComp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[  1%] Building CXX object rtc/Joystick/CMakeFiles/JoystickComp.dir/Joystick.o
[  1%] Generating DataLoggerService.hh, DataLoggerServiceSk.cpp, DataLoggerServiceDynSk.cpp
In file included from /home/mohammad/catkin_ws/lipm/hrpsys-base/rtc/Joystick/Joystick.cpp:10:0:
/home/mohammad/catkin_ws/lipm/hrpsys-base/rtc/Joystick/Joystick.h:13:36: fatal error: rtm/idl/BasicDataType.hh: No such file or directory
compilation terminated.
rtc/Joystick/CMakeFiles/JoystickComp.dir/build.make:75: recipe for target 'rtc/Joystick/CMakeFiles/JoystickComp.dir/Joystick.o' failed
make[2]: *** [rtc/Joystick/CMakeFiles/JoystickComp.dir/Joystick.o] Error 1
CMakeFiles/Makefile2:1167: recipe for target 'rtc/Joystick/CMakeFiles/JoystickComp.dir/all' failed
make[1]: *** [rtc/Joystick/CMakeFiles/JoystickComp.dir/all] Error 2
[  1%] Generating StateHolderService.hh, StateHolderServiceSk.cpp, StateHolderServiceDynSk.cpp
[  1%] Generating RobotHardwareService.hh, RobotHardwareServiceSk.cpp, RobotHardwareServiceDynSk.cpp
[  2%] Generating WavPlayerService.hh, WavPlayerServiceSk.cpp, WavPlayerServiceDynSk.cpp
[  2%] Generating SequencePlayerService.hh, SequencePlayerServiceSk.cpp, SequencePlayerServiceDynSk.cpp
[  2%] Generating ForwardKinematicsService.hh, ForwardKinematicsServiceSk.cpp, ForwardKinematicsServiceDynSk.cpp
[  2%] Generating ExecutionProfileService.hh, ExecutionProfileServiceSk.cpp, ExecutionProfileServiceDynSk.cpp
[  2%] Generating OGMap3DService.hh, OGMap3DServiceSk.cpp, OGMap3DServiceDynSk.cpp
[  3%] Generating NullService.hh, NullServiceSk.cpp, NullServiceDynSk.cpp
[  3%] Generating EmergencyStopperService.hh, EmergencyStopperServiceSk.cpp, EmergencyStopperServiceDynSk.cpp
[  3%] Generating TimeKeeperService.hh, TimeKeeperServiceSk.cpp, TimeKeeperServiceDynSk.cpp
[  3%] Generating Img.hh, ImgSk.cpp, ImgDynSk.cpp
[  3%] Generating HRPDataTypes.hh, HRPDataTypesSk.cpp, HRPDataTypesDynSk.cpp
[  4%] Generating pointcloud.hh, pointcloudSk.cpp, pointcloudDynSk.cpp
[  4%] Generating ImpedanceControllerService.hh, ImpedanceControllerServiceSk.cpp, ImpedanceControllerServiceDynSk.cpp
[  4%] Generating SoftErrorLimiterService.hh, SoftErrorLimiterServiceSk.cpp, SoftErrorLimiterServiceDynSk.cpp
[  4%] Generating CollisionDetectorService.hh, CollisionDetectorServiceSk.cpp, CollisionDetectorServiceDynSk.cpp
[  5%] Generating GraspControllerService.hh, GraspControllerServiceSk.cpp, GraspControllerServiceDynSk.cpp
[  5%] Generating TorqueFilterService.hh, TorqueFilterServiceSk.cpp, TorqueFilterServiceDynSk.cpp
[  5%] Generating KalmanFilterService.hh, KalmanFilterServiceSk.cpp, KalmanFilterServiceDynSk.cpp
[  5%] Generating VirtualForceSensorService.hh, VirtualForceSensorServiceSk.cpp, VirtualForceSensorServiceDynSk.cpp
[  5%] Generating StabilizerService.hh, StabilizerServiceSk.cpp, StabilizerServiceDynSk.cpp
[  5%] Generating AutoBalancerService.hh, AutoBalancerServiceSk.cpp, AutoBalancerServiceDynSk.cpp
[  6%] Generating RemoveForceSensorLinkOffsetService.hh, RemoveForceSensorLinkOffsetServiceSk.cpp, RemoveForceSensorLinkOffsetServiceDynSk.cpp
[  6%] Generating ServoControllerService.hh, ServoControllerServiceSk.cpp, ServoControllerServiceDynSk.cpp
[  6%] Generating TorqueControllerService.hh, TorqueControllerServiceSk.cpp, TorqueControllerServiceDynSk.cpp
[  6%] Generating ThermoLimiterService.hh, ThermoLimiterServiceSk.cpp, ThermoLimiterServiceDynSk.cpp
[  6%] Generating ReferenceForceUpdaterService.hh, ReferenceForceUpdaterServiceSk.cpp, ReferenceForceUpdaterServiceDynSk.cpp
[  6%] Generating AccelerationFilterService.hh, AccelerationFilterServiceSk.cpp, AccelerationFilterServiceDynSk.cpp
[  7%] Generating ObjectContactTurnaroundDetectorService.hh, ObjectContactTurnaroundDetectorServiceSk.cpp, ObjectContactTurnaroundDetectorServiceDynSk.cpp
Scanning dependencies of target hrpsysBaseStub
[  7%] Building CXX object idl/CMakeFiles/hrpsysBaseStub.dir/StateHolderServiceSk.o
[  7%] Building CXX object idl/CMakeFiles/hrpsysBaseStub.dir/DataLoggerServiceSk.o
[  7%] Building CXX object idl/CMakeFiles/hrpsysBaseStub.dir/DataLoggerServiceDynSk.o
[  7%] Linking CXX shared library ../libhrpIo.so
[  8%] Building CXX object idl/CMakeFiles/hrpsysBaseStub.dir/StateHolderServiceDynSk.o
[  8%] Built target hrpIo
[  8%] Building CXX object idl/CMakeFiles/hrpsysBaseStub.dir/RobotHardwareServiceSk.o
In file included from /home/mohammad/catkin_ws/lipm/hrpsys-base/build/idl/RobotHardwareServiceSk.cpp:3:0:
/home/mohammad/catkin_ws/lipm/hrpsys-base/build/idl/RobotHardwareService.hh:23:28: fatal error: BasicDataType.hh: No such file or directory
compilation terminated.
idl/CMakeFiles/hrpsysBaseStub.dir/build.make:424: recipe for target 'idl/CMakeFiles/hrpsysBaseStub.dir/RobotHardwareServiceSk.o' failed
make[2]: *** [idl/CMakeFiles/hrpsysBaseStub.dir/RobotHardwareServiceSk.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:108: recipe for target 'idl/CMakeFiles/hrpsysBaseStub.dir/all' failed
make[1]: *** [idl/CMakeFiles/hrpsysBaseStub.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2



Also this is cmake output:
-- The C compiler identification is GNU 5.5.0
-- The CXX compiler identification is GNU 5.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Found OpenRTM-aist 1.1.2 in /usr/local
-- Found OpenHRP 3.1.9 in /usr/local
-- OPENHRP_DEFINITIONS: 
-- REMOVE -Ox option from OPENHRP_DEFINITIONS, use CMAKE_BUILD_TYPE
-- OPENHRP_DEFINITIONS: 
-- Compile with Release
--  -- CMAKE_C_FLAGS / CMAKE_CXX_FLAGS  / 
--  -- CMAKE_C_FLAGS_DEBUG / CMAKE_CXX_FLAGS_DEBUG -g / -g
--  -- CMAKE_C_FLAGS_RELEASE / CMAKE_CXX_FLAGS_RELEASE -O3 -DNDEBUG / -O3 -DNDEBUG
--  -- CMAKE_C_FLAGS_RELWITHDEBINFO / CMAKE_CXX_FLAGS_RELWITHDEBINFO -O2 -g -DNDEBUG / -O2 -g -DNDEBUG
-- Found LibXml2: /usr/lib/x86_64-linux-gnu/libxml2.so (found version "2.9.3") 
-- Found Qhull in /usr
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found SDL: /usr/lib/x86_64-linux-gnu/libSDLmain.a;/usr/lib/x86_64-linux-gnu/libSDL.so;-lpthread (found version "1.2.15") 
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so   
-- Found GLUT: /usr/lib/x86_64-linux-gnu/libglut.so  
-- Checking for module 'opencv'
--   No package 'opencv' found
-- Checking for module 'opencv-2.3.1'
--   No package 'opencv-2.3.1' found
CMake Warning at CMakeLists.txt:155 (message):
  opencv not found


-- Checking for module 'glew'
--   Found glew, version 1.13.0
CMake Warning at CMakeLists.txt:162 (find_package):
  By not providing "FindPCL.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "PCL", but
  CMake did not find one.

  Could not find a package configuration file provided by "PCL" with any of
  the following names:

    PCLConfig.cmake
    pcl-config.cmake

  Add the installation prefix of "PCL" to CMAKE_PREFIX_PATH or set "PCL_DIR"
  to a directory containing one of the above files.  If "PCL" provides a
  separate development package or SDK, be sure it has been installed.


-- Looking for Eigen - found
CMake Warning (dev) at CMakeLists.txt:195 (add_definitions):
  Policy CMP0005 is not set: Preprocessor definition values are now escaped
  automatically.  Run "cmake --help-policy CMP0005" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- compile iob with -DROBOT_IOB_VERSION=4
Check if /home/mohammad/catkin_ws/lipm/hrpsys-base/idl/DataLoggerService.idl exists
Check if /home/mohammad/catkin_ws/lipm/hrpsys-base/idl/StateHolderService.idl exists
Check if /home/mohammad/catkin_ws/lipm/hrpsys-base/idl/RobotHardwareService.idl exists
Check if /home/mohammad/catkin_ws/lipm/hrpsys-base/idl/WavPlayerService.idl exists
Check if /home/mohammad/catkin_ws/lipm/hrpsys-base/idl/SequencePlayerService.idl exists
Check if /home/mohammad/catkin_ws/lipm/hrpsys-base/idl/ForwardKinematicsService.idl exists
Check if /home/mohammad/catkin_ws/lipm/hrpsys-base/idl/ExecutionProfileService.idl exists
Check if /home/mohammad/catkin_ws/lipm/hrpsys-base/idl/OGMap3DService.idl exists
Check if /home/mohammad/catkin_ws/lipm/hrpsys-base/idl/NullService.idl exists
Check if /home/mohammad/catkin_ws/lipm/hrpsys-base/idl/EmergencyStopperService.idl exists
Check if /home/mohammad/catkin_ws/lipm/hrpsys-base/idl/TimeKeeperService.idl exists
Check if /home/mohammad/catkin_ws/lipm/hrpsys-base/idl/Img.idl exists
Check if /home/mohammad/catkin_ws/lipm/hrpsys-base/idl/HRPDataTypes.idl exists
Check if /home/mohammad/catkin_ws/lipm/hrpsys-base/idl/pointcloud.idl exists
Check if /home/mohammad/catkin_ws/lipm/hrpsys-base/idl/ImpedanceControllerService.idl exists
Check if /home/mohammad/catkin_ws/lipm/hrpsys-base/idl/SoftErrorLimiterService.idl exists
Check if /home/mohammad/catkin_ws/lipm/hrpsys-base/idl/CollisionDetectorService.idl exists
Check if /home/mohammad/catkin_ws/lipm/hrpsys-base/idl/GraspControllerService.idl exists
Check if /home/mohammad/catkin_ws/lipm/hrpsys-base/idl/TorqueFilterService.idl exists
Check if /home/mohammad/catkin_ws/lipm/hrpsys-base/idl/KalmanFilterService.idl exists
Check if /home/mohammad/catkin_ws/lipm/hrpsys-base/idl/VirtualForceSensorService.idl exists
Check if /home/mohammad/catkin_ws/lipm/hrpsys-base/idl/StabilizerService.idl exists
Check if /home/mohammad/catkin_ws/lipm/hrpsys-base/idl/AutoBalancerService.idl exists
Check if /home/mohammad/catkin_ws/lipm/hrpsys-base/idl/RemoveForceSensorLinkOffsetService.idl exists
Check if /home/mohammad/catkin_ws/lipm/hrpsys-base/idl/ServoControllerService.idl exists
Check if /home/mohammad/catkin_ws/lipm/hrpsys-base/idl/TorqueControllerService.idl exists
Check if /home/mohammad/catkin_ws/lipm/hrpsys-base/idl/ThermoLimiterService.idl exists
Check if /home/mohammad/catkin_ws/lipm/hrpsys-base/idl/ReferenceForceUpdaterService.idl exists
Check if /home/mohammad/catkin_ws/lipm/hrpsys-base/idl/AccelerationFilterService.idl exists
Check if /home/mohammad/catkin_ws/lipm/hrpsys-base/idl/ObjectContactTurnaroundDetectorService.idl exists
Check if /home/mohammad/catkin_ws/lipm/hrpsys-base/idl/PCDLoaderService.idl exists
Check if /usr/local/share/OpenHRP-3.1/idl/OpenHRP/ClockGenerator.idl exists
Check if /usr/local/share/OpenHRP-3.1/idl/OpenHRP/CollisionDetector.idl exists
Check if /usr/local/share/OpenHRP-3.1/idl/OpenHRP/Controller.idl exists
Check if /usr/local/share/OpenHRP-3.1/idl/OpenHRP/DynamicsSimulator.idl exists
Check if /usr/local/share/OpenHRP-3.1/idl/OpenHRP/ModelLoader.idl exists
Check if /usr/local/share/OpenHRP-3.1/idl/OpenHRP/OnlineViewer.idl exists
Check if /usr/local/share/OpenHRP-3.1/idl/OpenHRP/OpenHRPCommon.idl exists
Check if /usr/local/share/OpenHRP-3.1/idl/OpenHRP/ViewSimulator.idl exists
Check if /usr/local/share/OpenHRP-3.1/idl/OpenHRP/World.idl exists
Check if /usr/local/share/OpenHRP-3.1/idl/OpenHRP/PathPlanner.idl exists
-- Use Normal Linux Thread
CMake Warning (dev) at ec/hrpEC/CMakeLists.txt:4 (link_directories):
  This command specifies the relative path

    io

  as a link directory.

  Policy CMP0015 is not set: link_directories() treats paths relative to the
  source dir.  Run "cmake --help-policy CMP0015" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- USE_QPOASES=OFF
CMake Warning (dev) at rtc/RobotHardware/CMakeLists.txt:3 (link_directories):
  This command specifies the relative path

    io

  as a link directory.

  Policy CMP0015 is not set: link_directories() treats paths relative to the
  source dir.  Run "cmake --help-policy CMP0015" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning at rtc/DataLogger/CMakeLists.txt:13 (find_package):
  By not providing "FindVTK.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "VTK", but
  CMake did not find one.

  Could not find a package configuration file provided by "VTK" (requested
  version 5.8) with any of the following names:

    VTKConfig.cmake
    vtk-config.cmake

  Add the installation prefix of "VTK" to CMAKE_PREFIX_PATH or set "VTK_DIR"
  to a directory containing one of the above files.  If "VTK" provides a
  separate development package or SDK, be sure it has been installed.


-- Found Irrlicht in /usr
-- Checking for module 'octomap'
--   Found octomap, version 1.8.1
CMake Warning (dev) at doc/CMakeLists.txt:74 (add_custom_target):
  Policy CMP0002 is not set: Logical target names must be globally unique.
  Run "cmake --help-policy CMP0002" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:226 (add_subdirectory):
  The source directory

    /home/mohammad/catkin_ws/lipm/hrpsys-base/test

  does not contain a CMakeLists.txt file.

  CMake does not support this case but it used to work accidentally and is
  being allowed for compatibility.

  Policy CMP0014 is not set: Input directories must have CMakeLists.txt.  Run
  "cmake --help-policy CMP0014" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
CMake Warning (dev) at sample/SampleRobot/rtc/CMakeLists.txt:44 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "SampleComponentService.hh" of target
  "SampleComponent" does not exist.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at sample/SampleRobot/rtc/CMakeLists.txt:45 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "SampleComponentService.hh" of target
  "SampleComponentComp" does not exist.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in ec/hrpEC/CMakeLists.txt:
  Policy CMP0081 is not set: Relative paths not allowed in LINK_DIRECTORIES
  target property.  Run "cmake --help-policy CMP0081" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Found relative path while evaluating link directories of "hrpEC":

    "io"

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in rtc/RobotHardware/CMakeLists.txt:
  Policy CMP0081 is not set: Relative paths not allowed in LINK_DIRECTORIES
  target property.  Run "cmake --help-policy CMP0081" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Found relative path while evaluating link directories of
  "RobotHardwareComp":

    "io"

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in rtc/RobotHardware/CMakeLists.txt:
  Policy CMP0081 is not set: Relative paths not allowed in LINK_DIRECTORIES
  target property.  Run "cmake --help-policy CMP0081" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Found relative path while evaluating link directories of "RobotHardware":

    "io"

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /home/mohammad/catkin_ws/lipm/hrpsys-base/build


Thank You

**Comment by mohamadmahdavian** [comment]
I was able to fix that problem.Now I am getting this error.Do you how I can solve it?

/////////////////////////////
[  0%] Generating PCDLoaderService.hh, PCDLoaderServiceSk.cpp, PCDLoaderServiceDynSk.cpp
[  0%] Building CXX object rtc/Joystick/CMakeFiles/Joystick.dir/Joystick.o
[  0%] Built target hrpIo
[  0%] Building CXX object rtc/Joystick/CMakeFiles/JoystickComp.dir/JoystickComp.o
[  1%] Building CXX object rtc/Joystick/CMakeFiles/JoystickComp.dir/Joystick.o
/home/mohammad/catkin_ws/lipm/hrpsys-base/idl/PCDLoaderService.idl:5: ExtendedDataTypes.idl: No such file or directory
/home/mohammad/catkin_ws/lipm/hrpsys-base/idl/PCDLoaderService.idl:12: Error in look-up of 'RTC::Pose3D': 'RTC' not found
/home/mohammad/catkin_ws/lipm/hrpsys-base/idl/PCDLoaderService.idl:13: Error in look-up of 'RTC::Point3D': 'RTC' not found
omniidl: 2 errors.
omniidl: Error running preprocessor
idl/CMakeFiles/hrpsysBaseStub.dir/build.make:361: recipe for target 'idl/PCDLoaderService.hh' failed
make[2]: *** [idl/PCDLoaderService.hh] Error 1
CMakeFiles/Makefile2:108: recipe for target 'idl/CMakeFiles/hrpsysBaseStub.dir/all' failed
make[1]: *** [idl/CMakeFiles/hrpsysBaseStub.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  1%] Building CXX object rtc/Joystick/CMakeFiles/JoystickComp.dir/js.o
[  1%] Linking CXX executable ../../bin/JoystickComp
[  1%] Linking CXX shared library ../../lib/Joystick.so
[  1%] Built target JoystickComp
[  1%] Built target Joystick
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

Thank You

**Comment by Aimiliospet** [comment]
@fkanehiro @ghost did you manage to solve the issue? I'm currently facing the last error with ubuntu 18.04 .
when i use make i get:
`[  0%] Generating PCDLoaderService.hh, PCDLoaderServiceSk.cpp, PCDLoaderServiceDynSk.cpp
omniidl: No files specified. Use 'omniidl -u' for usage.
idl/CMakeFiles/hrpsysBaseStub.dir/build.make:361: recipe for target 'idl/PCDLoaderService.hh' failed
make[2]: *** [idl/PCDLoaderService.hh] Error 1
CMakeFiles/Makefile2:103: recipe for target 'idl/CMakeFiles/hrpsysBaseStub.dir/all' failed
make[1]: *** [idl/CMakeFiles/hrpsysBaseStub.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
`
