### ISSUE TITLE
複合干渉のある関節の関節角度リミットを考慮する

### ISSUE THREAD

**Issue by fkanehiro** [fkanehiro/hrpsys-base#135]
_From [nothewo...@gmail.com](https://code.google.com/u/101361599614986353837/) on September 17, 2013 19:29:10_

HRP２の股関節・７自由度アームの手首などのように、
ModelLoaderのllimit, ulimitが隣接する軸間の
関節角度に応じてハードウェアリミットが変わるような軸の、
関節リミットを考慮するものが必要に思い、
まずは要望ということでチケットにさせていただきます。

_Original issue: http://code.google.com/p/hrpsys-base/issues/detail?id=135_

**Comment by snozawa** [comment]
https://github.com/fkanehiro/hrpsys-base/pull/433
で対応しましたので、closeをお願いいたします。
