### ISSUE TITLE
プラグインを起動した時にrevision番号が分かるようにする

### ISSUE THREAD

**Issue by fkanehiro** [fkanehiro/hrpsys-base#141]
_From [kei.ok...@gmail.com](https://code.google.com/u/106507436521441488688/) on September 27, 2013 14:38:25_

http://code.google.com/p/rtm-ros-robotics/issues/detail?id=217 にあるように，最新だと動いています→最新のつもりですが，，，というやり取りをなくすために
プラグインの起動時にrevisoin番号を出すようにしたいとおもいます，ってまえも何処かでやった気がする．nervousだったか？

_Original issue: http://code.google.com/p/hrpsys-base/issues/detail?id=141_

**Comment by snozawa** [comment]
こちら
https://github.com/fkanehiro/hrpsys-base/commit/1d0e9c52aa39f9519c74e79c22dc778ade8d17d6
の変更でhrpsys-baseのバージョンが取得できるようになってますので、closeで大丈夫だと思います。
