### ISSUE TITLE
impedance制御のref-forceを補間・更新したい

### ISSUE THREAD

**Issue by fkanehiro** [fkanehiro/hrpsys-base#147]
_From [muro...@jsk.imi.i.u-tokyo.ac.jp](https://code.google.com/u/106974633471422031473/) on October 21, 2013 17:57:14_

impedance制御のref-forceを
hrpsysの制御ループの中で，
補間・更新したいです．

現状はref-forceをeusなどから変更したときに
不連続に変更されてしまいますが，
Autobalancerと合わせて安定に使うためには
なめらかに補完する必要があります．

また，
(ドア開けの際にHRP2がやっていたように)
eusからではなくhrpsysの制御ループの中で
センサフィードバックでref-forceを
更新したいです．

_Original issue: http://code.google.com/p/hrpsys-base/issues/detail?id=147_

**Comment by snozawa** [comment]
こちらはほぼ
https://github.com/fkanehiro/hrpsys-base/pull/434
で解決されましたので、closeでお願いします。
（更新については別途対応したいと思います）
