### ISSUE TITLE
writeDigitalOutputWithMask often returns true on simulation

### ISSUE THREAD

**Issue by 130s** [fkanehiro/hrpsys-base#404]
`writeDigitalOutputWithMask` は，(API doc 等はっきり書かれてないように思いますが) DIO ハードウェアが無ければここは必ず False が返って来て欲しい所だと思っていますが，何らかの条件で True が帰ってくることがあるようです．

https://github.com/fkanehiro/hrpsys-base/blob/525ac450a01e5485960cf13911879ce2ccfd6266/rtc/RobotHardware/RobotHardwareService_impl.cpp#L138

```
CORBA::Boolean RobotHardwareService_impl::writeDigitalOutputWithMask(const ::OpenHRP::RobotHardwareService::OctSequence& dout, const ::OpenHRP::RobotHardwareService::OctSequence& mask)
{
return m_robot->writeDigitalOutputWithMask((const char *)(dout.get_buffer()), (const char *)(mask.get_buffer()));
}
```

例えば下流の travis で，https://travis-ci.org/tork-a/rtmros_nextage/jobs/40760573#L3096

```
True is not false
File "/usr/lib/python2.7/unittest/case.py", line 327, in run
testMethod()
File "/home/travis/ros/ws_rtmros_nextage/install/share/nextage_ros_bridge/test/test_handlight.py", line 106, in test_handlight_l_04
self.assertFalse(result)
File "/usr/lib/python2.7/unittest/case.py", line 414, in assertFalse
raise self.failureException(msg)
```

`True is not false` と言われているのは，test_handlight_l_04 というテストケースが assertFalse している値が True になっていて，この値は上流まで行くと `writeDigitalOutputWithMask` から返って来ます．
@emijah

**Comment by k-okada** [comment]
https://github.com/fkanehiro/hrpsys-base/blob/master/python/hrpsys_config.py#L1284 seems it is ALWAYS returns True in simulaiton, if you want to change this behavior, please create enew PR

close #404

**Comment by 130s** [comment]
[この PR のテスト](https://github.com/tork-a/rtmros_nextage/pull/154)も通っているしどうやらどこかで変更を入れて頂いたようですね．ありがとうございます．

**Comment by k-okada** [comment]
テストはベトのところではなくて，このPRのhttps://github.com/tork-a/rtmros_nextage/pull/154/files
を変えたので通っています．強引に現状合わせでFalse->Trueにしていますがこれでいいかわかっていません？

https://github.com/fkanehiro/hrpsys-base/issues/404
でfalseが期待されるけとときどきTrueになる，と書いてあるものの，実際には必ずTrueになる
https://github.com/fkanehiro/hrpsys-base/blob/master/python/hrpsys_config.py#L1319
ようになっているようです．

--
◉ Kei Okada


2015-03-14 11:22 GMT+09:00 Isaac I.Y. Saito <notifications@github.com>:
