### ISSUE TITLE
Release 315.3.1 (or else)

### ISSUE THREAD

**Issue by 130s** [fkanehiro/hrpsys-base#522]
https://github.com/fkanehiro/hrpsys-base/pull/519 (・それに依存する https://github.com/start-jsk/rtmros_hironx/issues/333) が Hiro・NXO ユーザにクリティカルなのですが，パッチバージョンのリリースを検討頂けると嬉しいです．

リリース希望する人が https://github.com/fkanehiro/hrpsys-base/pull/503 のような PR を出すのかも知れないですが，そのタイミングはどこかでコンセンサスが取られているのかわからないので，こちらで伺いまで．

**Comment by 130s** [comment]
この件いかがでしょうか？
@k-okada @fkanehiro

**Comment by k-okada** [comment]
すいません．travisがようやく通りつつ有る気がするので，ひと通り出ているPRが通ったらリリースしようと思っていました．
ところで，#519は最初に:goInitial しなくても大丈夫にしました，という話でクリティカル，というほどのものでもない
（実機もっていたらかならずgoInitialするはず）という認識なんですが，そうでもないんでしょうか？

--
◉ Kei Okada

**Comment by 130s** [comment]
https://github.com/ros/rosdistro/pull/7802 ありがとうございました．
