### ISSUE TITLE
hrpsys-simulatorで物体/環境モデルのでてくる位置がおかしい

### ISSUE THREAD

**Issue by snozawa** [fkanehiro/hrpsys-base#560]
hrpsys-simulatorで物体・環境モデルの初期位置を
```
   <property name="WAIST.translation" value="-5.83  -0.2  -0.6096"/>
```
などで設定していると以前はこの初期位置に環境モデルなどがでてきました。

今実行すると、最初の時刻０のときにここにあるのですが、
次の時刻に原点位置に戻されているようにみえます。

再現するコードは
```
rtmlaunch hrpsys samplerobot.launch PROJECT_FILE:=`rospack find hrpsys`/samples/SampleRobot/SampleRobot.TerrainFloor.StairDown.xml
```
です。
以前は
http://wiki.ros.org/rtmros_common/Tutorials/WorkingWithEusLisp#Terrain_Walk_examples
のようにふせいちコースの途中にロボットが位置するような初期位置関係にでてましたが、今は環境モデルが原点位置（ロボットがふせいちコースの一番はじっこ）に位置してしまいます。

よろしくお願いします。

**Comment by k-okada** [comment]
#561で解決かな

**Comment by snozawa** [comment]
#561がマージされてmasterをgit pullしてきて、治っていることを確認しました。
