### ISSUE TITLE
hrpsys devel jobs are trying and failing to building the documentation

### ISSUE THREAD

**Issue by tfoote** [fkanehiro/hrpsys-base#629]
The last devel builds here was over an hour: http://54.183.26.131:8080/job/Idev__hrpsys__ubuntu_trusty_amd64/104/consoleFull

This is taking a long time and is mostly failing due to documentation dependencies not being met, such as dot missing. 
```
00:07:13.879 error: Problems running dot: exit code=127, command='dot', arguments='"/tmp/catkin_workspace/build_isolated/hrpsys/install/doc/html/inherit_graph_17.dot" -Tpng -o "/tmp/catkin_workspace/build_isolated/hrpsys/install/doc/html/inherit_graph_17.png"'
00:07:13.879 sh: 1: dot: not found
```

**Comment by k-okada** [comment]
thanks add depend to graphviz at #630
