### ISSUE TITLE
release してもいいでしょうか？

### ISSUE THREAD

**Issue by k-okada** [fkanehiro/hrpsys-base#715]
個人的にはいくつかseqplayer周りで更新が終わったと思っているのでリリースしたいんですが，
他のところも一段落ついたというかんじになっているでしょうか？

**Comment by snozawa** [comment]
私個人の作業的にはOKです。
seqplayerまわりもいくつか確認・テスト追加などしたい部分がありますが、直近ではやらなさそうなのでreleaseをすすめていただいてOKです。https://github.com/fkanehiro/hrpsys-base/issues/707

**Comment by k-okada** [comment]
done https://github.com/fkanehiro/hrpsys-base/pull/716
