### ISSUE TITLE
choreonoidと接続するときはどうするか

### ISSUE THREAD

**Issue by YoheiKakiuchi** [fkanehiro/hrpsys-base#734]
少し場違いかもしれませんが、
choreonoidとhrpsys-baseを接続して使う（感覚としては、hrpsys-simulatorのかわりにchoreonoidのシミュレータを使う）場合に、どのような方法がありますでしょうか？

choreonoidのBodyRTC等を使うと、接続はできるようには思うのですが、同期がとれないようにおもいます。
choreonoid側からタイミングを出すことは可能なようにも思うのですが、hrpsys側が遅い時に、choreonoid側の
シミュレーションを同期させる方法はあるでしょうか？

**Comment by fkanehiro** [comment]
hrpsys-baseの場合と同様外部トリガ付き実行コンテキストを使って下さい。
シミュレータのメインループがトリガをかけます。
