### ISSUE TITLE
release new version

### ISSUE THREAD

**Issue by snozawa** [fkanehiro/hrpsys-base#780]
作業が一段落してないですが、rtmros_commonのテストで確認したいところがありますので
一度new versionをリリースしていただけると助かります。

**Comment by k-okada** [comment]
１段落してからにしません？

--
◉ Kei Okada


2015-08-28 15:38 GMT+09:00 Shunichi Nozawa <notifications@github.com>:

**Comment by snozawa** [comment]
お手数だとは存じますが、やはりそうしたほうが良いでしょうか。

**Comment by k-okada** [comment]
わからないけど，hrpsysのなんかの機能を確認したいならhrpsysで確認して，それが動いたら，
rtmros_commonという風にきり分けられないのかな．

--
◉ Kei Okada

**Comment by snozawa** [comment]
rtmros_commonにeuslispのインターフェースがあるので、主にidlレベルで変更があると、
unstable rtcでもdebの場合はdebチェックが必要です。

実はrtm-ros-robot-interface.lをhrpsys-baseにコミットさせていただくことができれば一番ラクですが、ちょっとアレなきがするので、
rtmros_commonのほうで最近追加したeuslispチェックはUSE_DEB=falseのときのみチェックするようにします。
（もともtそうするつもりでしたが、なってないことがわかったので今なおしています）

**Comment by k-okada** [comment]
なるほど．それはそれがいいですね．
一段落したら教えて下さい．

--
◉ Kei Okada


2015-08-28 16:10 GMT+09:00 Shunichi Nozawa <notifications@github.com>:

**Comment by snozawa** [comment]
了解です。ありがとうございます。
