### ISSUE TITLE
interprocess_semaphoreの利用について

### ISSUE THREAD

**Issue by snozawa** [fkanehiro/hrpsys-base#969]
rtc以下の
```
rtc/StateHolder/StateHolder.h:  boost::interprocess::interprocess_semaphore m_waitSem, m_timeSem;
rtc/RobotHardware/robot.h:    boost::interprocess::interprocess_semaphore wait_sem;
rtc/SequencePlayer/SequencePlayer.h:  boost::interprocess::interprocess_semaphore m_waitSem;
```
の主に３箇所くらいでboostのinterprocess_semaphoreが使われているのですが、
boostでないsemaphore.hをお使いでなくこちらをお使いの理由はなにになりますでしょうか。
ちなみに、boost versionが1.35.0以前だとboostのinterprocess_semaphoreが使えない状況のようです。

よろしくお願いいたします。

**Comment by fkanehiro** [comment]
え～っと、正直記憶にありません。
普通のセマフォでいい気がします。

**Comment by snozawa** [comment]
ありがとうございます

> 普通のセマフォでいい気がします。

boost versionが1.35.0以前でも（パッチなく）動作するようにしようと思っているのですが、
- interprocess_semaphore=>semaphoreに変更する、多分大丈夫そうですが挙動はかわりそうです
- boost versionを参照して、新しければ現状と同じ挙動、古ければsemaphoreになるようにifdefなどで対応する

のどちらがよろしいでしょうか。

**Comment by fkanehiro** [comment]
スッキリと統一する、でいいんじゃないでしょうか。

2016年4月7日 10:29 Shunichi Nozawa <notifications@github.com>:

**Comment by snozawa** [comment]
https://github.com/fkanehiro/hrpsys-base/issues/970
でsemaphore.hを使うように統一いたさいmした。

ありがとうございました。
